ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_A_U35_MwScheme_UFO_v3_1'
     $ //'-cHW_massless'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_387 = ', GC_387
      WRITE(*,2) 'GC_400 = ', GC_400
      WRITE(*,2) 'GC_809 = ', GC_809
      WRITE(*,2) 'GC_1073 = ', GC_1073
