ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_MW0 = ', MDL_MW0
      WRITE(*,*) 'mdl_Gf = ', MDL_GF
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'mdl_ymdo = ', MDL_YMDO
      WRITE(*,*) 'mdl_ymb = ', MDL_YMB
      WRITE(*,*) 'mdl_ymt = ', MDL_YMT
      WRITE(*,*) 'mdl_ymtau = ', MDL_YMTAU
      WRITE(*,*) 'mdl_LambdaSMEFT = ', MDL_LAMBDASMEFT
      WRITE(*,*) 'mdl_cW = ', MDL_CW
      WRITE(*,*) 'mdl_MZ = ', MDL_MZ
      WRITE(*,*) 'mdl_MTA = ', MDL_MTA
      WRITE(*,*) 'mdl_MT = ', MDL_MT
      WRITE(*,*) 'mdl_MB = ', MDL_MB
      WRITE(*,*) 'mdl_MH = ', MDL_MH
      WRITE(*,*) 'mdl_WZ = ', MDL_WZ
      WRITE(*,*) 'mdl_WW = ', MDL_WW
      WRITE(*,*) 'mdl_WT = ', MDL_WT
      WRITE(*,*) 'mdl_WH = ', MDL_WH
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_ymm = ', MDL_YMM
      WRITE(*,*) 'mdl_yme = ', MDL_YME
      WRITE(*,*) 'mdl_ymc = ', MDL_YMC
      WRITE(*,*) 'mdl_yms = ', MDL_YMS
      WRITE(*,*) 'mdl_ymup = ', MDL_YMUP
      WRITE(*,*) 'mdl_conjg__CKM3x3 = ', MDL_CONJG__CKM3X3
      WRITE(*,*) 'mdl_cH = ', MDL_CH
      WRITE(*,*) 'mdl_cHB = ', MDL_CHB
      WRITE(*,*) 'mdl_CKM2x2 = ', MDL_CKM2X2
      WRITE(*,*) 'mdl_CKM1x1 = ', MDL_CKM1X1
      WRITE(*,*) 'mdl_conjg__CKM1x1 = ', MDL_CONJG__CKM1X1
      WRITE(*,*) 'mdl_dGf = ', MDL_DGF
      WRITE(*,*) 'mdl_CKM3x3 = ', MDL_CKM3X3
      WRITE(*,*) 'mdl_dMH2 = ', MDL_DMH2
      WRITE(*,*) 'mdl_conjg__CKM2x2 = ', MDL_CONJG__CKM2X2
      WRITE(*,*) 'mdl_dg1 = ', MDL_DG1
      WRITE(*,*) 'mdl_cHW = ', MDL_CHW
      WRITE(*,*) 'mdl_dgw = ', MDL_DGW
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_MW = ', MDL_MW
      WRITE(*,*) 'mdl_nb__2__exp__0_25 = ', MDL_NB__2__EXP__0_25
      WRITE(*,*) 'mdl_MH__exp__2 = ', MDL_MH__EXP__2
      WRITE(*,*) 'mdl_sqrt__2 = ', MDL_SQRT__2
      WRITE(*,*) 'mdl_MW__exp__2 = ', MDL_MW__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__2 = ', MDL_MZ__EXP__2
      WRITE(*,*) 'mdl_sth2 = ', MDL_STH2
      WRITE(*,*) 'mdl_MH__exp__6 = ', MDL_MH__EXP__6
      WRITE(*,*) 'mdl_MT__exp__6 = ', MDL_MT__EXP__6
      WRITE(*,*) 'mdl_MH__exp__4 = ', MDL_MH__EXP__4
      WRITE(*,*) 'mdl_MT__exp__4 = ', MDL_MT__EXP__4
      WRITE(*,*) 'mdl_MT__exp__2 = ', MDL_MT__EXP__2
      WRITE(*,*) 'mdl_LambdaSMEFT__exp__2 = ', MDL_LAMBDASMEFT__EXP__2
      WRITE(*,*) 'mdl_cth = ', MDL_CTH
      WRITE(*,*) 'mdl_sqrt__sth2 = ', MDL_SQRT__STH2
      WRITE(*,*) 'mdl_sth = ', MDL_STH
      WRITE(*,*) 'mdl_MW0__exp__6 = ', MDL_MW0__EXP__6
      WRITE(*,*) 'mdl_MW0__exp__4 = ', MDL_MW0__EXP__4
      WRITE(*,*) 'mdl_MW0__exp__2 = ', MDL_MW0__EXP__2
      WRITE(*,*) 'mdl_MZ__exp__4 = ', MDL_MZ__EXP__4
      WRITE(*,*) 'mdl_MZ__exp__6 = ', MDL_MZ__EXP__6
      WRITE(*,*) 'mdl_cth__exp__2 = ', MDL_CTH__EXP__2
      WRITE(*,*) 'mdl_sth__exp__2 = ', MDL_STH__EXP__2
      WRITE(*,*) 'mdl_sth__exp__3 = ', MDL_STH__EXP__3
      WRITE(*,*) 'mdl_cth__exp__3 = ', MDL_CTH__EXP__3
      WRITE(*,*) 'mdl_sth__exp__4 = ', MDL_STH__EXP__4
      WRITE(*,*) 'mdl_sqrt__Gf = ', MDL_SQRT__GF
      WRITE(*,*) 'mdl_vevhat = ', MDL_VEVHAT
      WRITE(*,*) 'mdl_lam = ', MDL_LAM
      WRITE(*,*) 'mdl_aEW = ', MDL_AEW
      WRITE(*,*) 'mdl_yb = ', MDL_YB
      WRITE(*,*) 'mdl_yc = ', MDL_YC
      WRITE(*,*) 'mdl_ydo = ', MDL_YDO
      WRITE(*,*) 'mdl_ye = ', MDL_YE
      WRITE(*,*) 'mdl_ym = ', MDL_YM
      WRITE(*,*) 'mdl_ys = ', MDL_YS
      WRITE(*,*) 'mdl_yt = ', MDL_YT
      WRITE(*,*) 'mdl_ytau = ', MDL_YTAU
      WRITE(*,*) 'mdl_yup = ', MDL_YUP
      WRITE(*,*) 'mdl_vevhat__exp__2 = ', MDL_VEVHAT__EXP__2
      WRITE(*,*) 'mdl_barlam = ', MDL_BARLAM
      WRITE(*,*) 'mdl_vevT = ', MDL_VEVT
      WRITE(*,*) 'mdl_sqrt__aEW = ', MDL_SQRT__AEW
      WRITE(*,*) 'mdl_ee = ', MDL_EE
      WRITE(*,*) 'mdl_gwsh = ', MDL_GWSH
      WRITE(*,*) 'mdl_vev = ', MDL_VEV
      WRITE(*,*) 'mdl_g1 = ', MDL_G1
      WRITE(*,*) 'mdl_gw = ', MDL_GW
      WRITE(*,*) 'mdl_ee__exp__2 = ', MDL_EE__EXP__2
      WRITE(*,*) 'mdl_gHaa = ', MDL_GHAA
      WRITE(*,*) 'mdl_gHza = ', MDL_GHZA
      WRITE(*,*) 'mdl_g1sh = ', MDL_G1SH
      WRITE(*,*) 'mdl_I1d11 = ', MDL_I1D11
      WRITE(*,*) 'mdl_I1d22 = ', MDL_I1D22
      WRITE(*,*) 'mdl_I1d33 = ', MDL_I1D33
      WRITE(*,*) 'mdl_I2d11 = ', MDL_I2D11
      WRITE(*,*) 'mdl_I2d22 = ', MDL_I2D22
      WRITE(*,*) 'mdl_I2d33 = ', MDL_I2D33
      WRITE(*,*) 'mdl_I3d11 = ', MDL_I3D11
      WRITE(*,*) 'mdl_I3d22 = ', MDL_I3D22
      WRITE(*,*) 'mdl_I3d33 = ', MDL_I3D33
      WRITE(*,*) 'mdl_I4d11 = ', MDL_I4D11
      WRITE(*,*) 'mdl_I4d22 = ', MDL_I4D22
      WRITE(*,*) 'mdl_I4d33 = ', MDL_I4D33
      WRITE(*,*) 'mdl_I5d11 = ', MDL_I5D11
      WRITE(*,*) 'mdl_I5d22 = ', MDL_I5D22
      WRITE(*,*) 'mdl_I5d33 = ', MDL_I5D33
      WRITE(*,*) 'mdl_I6d11 = ', MDL_I6D11
      WRITE(*,*) 'mdl_I6d22 = ', MDL_I6D22
      WRITE(*,*) 'mdl_I6d33 = ', MDL_I6D33
      WRITE(*,*) 'mdl_ee__exp__3 = ', MDL_EE__EXP__3
      WRITE(*,*) 'mdl_vevhat__exp__3 = ', MDL_VEVHAT__EXP__3
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_sqrt__aS = ', MDL_SQRT__AS
      WRITE(*,*) 'mdl_G__exp__2 = ', MDL_G__EXP__2
      WRITE(*,*) 'mdl_gHgg = ', MDL_GHGG
      WRITE(*,*) 'mdl_G__exp__3 = ', MDL_G__EXP__3
