ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SMEFTsim_A_U35_MwScheme_UFO_v3_1'
     $ //'-cW_massless'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_64 = ', GC_64
      WRITE(*,2) 'GC_345 = ', GC_345
      WRITE(*,2) 'GC_1 = ', GC_1
      WRITE(*,2) 'GC_2 = ', GC_2
      WRITE(*,2) 'GC_3 = ', GC_3
      WRITE(*,2) 'GC_255 = ', GC_255
      WRITE(*,2) 'GC_278 = ', GC_278
      WRITE(*,2) 'GC_280 = ', GC_280
      WRITE(*,2) 'GC_318 = ', GC_318
      WRITE(*,2) 'GC_328 = ', GC_328
      WRITE(*,2) 'GC_329 = ', GC_329
      WRITE(*,2) 'GC_330 = ', GC_330
      WRITE(*,2) 'GC_400 = ', GC_400
      WRITE(*,2) 'GC_809 = ', GC_809
      WRITE(*,2) 'GC_1073 = ', GC_1073
