# Si parte con gli istogrammi in output da ExRootAnalysis nella cartella "data"
#osservabili usate per ora: PT, Eta, mll, mjj


cd build;
make clean;
make;
make install;
cd ..;


./all_pt SM;
./all_pt cW_int;
./all_pt cW_quad;
./all_pt cHW_int;
./all_pt cHW_quad;
./all_pt cHWB_int;
./all_pt cHWB_quad;
./all_pt cHbox_int;
./all_pt cHbox_quad;
./all_pt cHDD_int;
./all_pt cHDD_quad;
./all_pt cW_int_0.4;
./all_pt cW_quad_0.4;
./all_pt cWtil_int;
./all_pt cWtil_quad;
./all_pt cHWtil_int;
./all_pt cHWtil_quad;
./all_pt cHWBtil_int;
./all_pt cHWBtil_quad;


./all_mll SM;
./all_mll cW_int;
./all_mll cW_quad;
./all_mll cHW_int;
./all_mll cHW_quad;
./all_mll cHWB_int;
./all_mll cHWB_quad;
./all_mll cHbox_int;
./all_mll cHbox_quad;
./all_mll cHDD_int;
./all_mll cHDD_quad;
./all_mll cW_int_0.4;
./all_mll cW_quad_0.4;
./all_mll cWtil_int;
./all_mll cWtil_quad;
./all_mll cHWtil_int;
./all_mll cHWtil_quad;
./all_mll cHWBtil_int;
./all_mll cHWBtil_quad;

./all_Eta SM;
./all_Eta cW_int;
./all_Eta cW_quad;
./all_Eta cHW_int;
./all_Eta cHW_quad;
./all_Eta cHWB_int;
./all_Eta cHWB_quad;
./all_Eta cHbox_int;
./all_Eta cHbox_quad;
./all_Eta cHDD_int;
./all_Eta cHDD_quad;
./all_Eta cW_int_0.4;
./all_Eta cW_quad_0.4;
./all_Eta cWtil_int;
./all_Eta cWtil_quad;
./all_Eta cHWtil_int;
./all_Eta cHWtil_quad;
./all_Eta cHWBtil_int;
./all_Eta cHWBtil_quad;

./all_mjj SM;
./all_mjj cW_int;
./all_mjj cW_quad;
./all_mjj cHW_int;
./all_mjj cHW_quad;
./all_mjj cHWB_int;
./all_mjj cHWB_quad;
./all_mjj cHbox_int;
./all_mjj cHbox_quad;
./all_mjj cHDD_int;
./all_mjj cHDD_quad;
./all_mjj cW_int_0.4;
./all_mjj cW_quad_0.4;
./all_mjj cWtil_int;
./all_mjj cWtil_quad;
./all_mjj cHWtil_int;
./all_mjj cHWtil_quad;
./all_mjj cHWBtil_int;
./all_mjj cHWBtil_quad;

cd histos/mll;
/home/nyykki/root/bin/hadd -f SM_cW_int.root SM.root cW_int.root;
/home/nyykki/root/bin/hadd -f SM_cW_quad.root SM.root cW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cW_int_quad.root SM.root cW_int.root cW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHW_int.root SM.root cHW_int.root;
/home/nyykki/root/bin/hadd -f SM_cHW_quad.root SM.root cHW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHW_int_quad.root SM.root cHW_int.root cHW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWB_int.root SM.root cHWB_int.root;
/home/nyykki/root/bin/hadd -f SM_cHWB_quad.root SM.root cHWB_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWB_int_quad.root SM.root cHWB_int.root cHWB_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHbox_int.root SM.root cHbox_int.root;
/home/nyykki/root/bin/hadd -f SM_cHbox_quad.root SM.root cHbox_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHbox_int_quad.root SM.root cHbox_int.root cHbox_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_int.root SM.root cHDD_int.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_quad.root SM.root cHDD_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_int_quad.root SM.root cHDD_int.root cHDD_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_int_quad.root SM.root cHDD_int.root cHDD_quad.root;
/home/nyykki/root/bin/hadd -f SM_cW_int_0.4.root SM.root cW_int_0.4.root;
/home/nyykki/root/bin/hadd -f SM_cW_quad_0.4.root SM.root cW_quad_0.4.root;
/home/nyykki/root/bin/hadd -f SM_cW_int_quad_0.4.root SM.root cW_int_0.4.root cW_quad_0.4.root;
/home/nyykki/root/bin/hadd -f SM_cWtil_int.root SM.root cWtil_int.root;
/home/nyykki/root/bin/hadd -f SM_cWtil_quad.root SM.root cWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cWtil_int_quad.root SM.root cWtil_int.root cWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWtil_int.root SM.root cHWtil_int.root;
/home/nyykki/root/bin/hadd -f SM_cHWtil_quad.root SM.root cHWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWtil_int_quad.root SM.root cHWtil_int.root cHWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWBtil_int.root SM.root cHWBtil_int.root;
/home/nyykki/root/bin/hadd -f SM_cHWBtil_quad.root SM.root cHWBtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWBtil_int_quad.root SM.root cHWBtil_int.root cHWBtil_quad.root;

cd ..;

cd Eta;
/home/nyykki/root/bin/hadd -f SM_cW_int.root SM.root cW_int.root;
/home/nyykki/root/bin/hadd -f SM_cW_quad.root SM.root cW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cW_int_quad.root SM.root cW_int.root cW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHW_int.root SM.root cHW_int.root;
/home/nyykki/root/bin/hadd -f SM_cHW_quad.root SM.root cHW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHW_int_quad.root SM.root cHW_int.root cHW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWB_int.root SM.root cHWB_int.root;
/home/nyykki/root/bin/hadd -f SM_cHWB_quad.root SM.root cHWB_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWB_int_quad.root SM.root cHWB_int.root cHWB_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHbox_int.root SM.root cHbox_int.root;
/home/nyykki/root/bin/hadd -f SM_cHbox_quad.root SM.root cHbox_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHbox_int_quad.root SM.root cHbox_int.root cHbox_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_int.root SM.root cHDD_int.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_quad.root SM.root cHDD_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_int_quad.root SM.root cHDD_int.root cHDD_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_int_quad.root SM.root cHDD_int.root cHDD_quad.root;
/home/nyykki/root/bin/hadd -f SM_cWtil_int.root SM.root cWtil_int.root;
/home/nyykki/root/bin/hadd -f SM_cWtil_quad.root SM.root cWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cWtil_int_quad.root SM.root cWtil_int.root cWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWtil_int.root SM.root cHWtil_int.root;
/home/nyykki/root/bin/hadd -f SM_cHWtil_quad.root SM.root cHWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWtil_int_quad.root SM.root cHWtil_int.root cHWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWBtil_int.root SM.root cHWBtil_int.root;
/home/nyykki/root/bin/hadd -f SM_cHWBtil_quad.root SM.root cHWBtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWBtil_int_quad.root SM.root cHWBtil_int.root cHWBtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cW_int_0.4.root SM.root cW_int_0.4.root;
/home/nyykki/root/bin/hadd -f SM_cW_quad_0.4.root SM.root cW_quad_0.4.root;
/home/nyykki/root/bin/hadd -f SM_cW_int_quad_0.4.root SM.root cW_int_0.4.root cW_quad_0.4.root;


cd ..;

cd PT;
/home/nyykki/root/bin/hadd -f SM_cW_int.root SM.root cW_int.root;
/home/nyykki/root/bin/hadd -f SM_cW_quad.root SM.root cW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cW_int_quad.root SM.root cW_int.root cW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHW_int.root SM.root cHW_int.root;
/home/nyykki/root/bin/hadd -f SM_cHW_quad.root SM.root cHW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHW_int_quad.root SM.root cHW_int.root cHW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWB_int.root SM.root cHWB_int.root;
/home/nyykki/root/bin/hadd -f SM_cHWB_quad.root SM.root cHWB_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWB_int_quad.root SM.root cHWB_int.root cHWB_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHbox_int.root SM.root cHbox_int.root;
/home/nyykki/root/bin/hadd -f SM_cHbox_quad.root SM.root cHbox_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHbox_int_quad.root SM.root cHbox_int.root cHbox_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_int.root SM.root cHDD_int.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_quad.root SM.root cHDD_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_int_quad.root SM.root cHDD_int.root cHDD_quad.root;
/home/nyykki/root/bin/hadd -f SM_cWtil_int.root SM.root cWtil_int.root;
/home/nyykki/root/bin/hadd -f SM_cWtil_quad.root SM.root cWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cWtil_int_quad.root SM.root cWtil_int.root cWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWtil_int.root SM.root cHWtil_int.root;
/home/nyykki/root/bin/hadd -f SM_cHWtil_quad.root SM.root cHWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWtil_int_quad.root SM.root cHWtil_int.root cHWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWBtil_int.root SM.root cHWBtil_int.root;
/home/nyykki/root/bin/hadd -f SM_cHWBtil_quad.root SM.root cHWBtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWBtil_int_quad.root SM.root cHWBtil_int.root cHWBtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cW_int_0.4.root SM.root cW_int_0.4.root;
/home/nyykki/root/bin/hadd -f SM_cW_quad_0.4.root SM.root cW_quad_0.4.root;
/home/nyykki/root/bin/hadd -f SM_cW_int_quad_0.4.root SM.root cW_int_0.4.root cW_quad_0.4.root;

cd ..;

cd mjj;
/home/nyykki/root/bin/hadd -f SM_cW_int.root SM.root cW_int.root;
/home/nyykki/root/bin/hadd -f SM_cW_quad.root SM.root cW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cW_int_quad.root SM.root cW_int.root cW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHW_int.root SM.root cHW_int.root;
/home/nyykki/root/bin/hadd -f SM_cHW_quad.root SM.root cHW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHW_int_quad.root SM.root cHW_int.root cHW_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWB_int.root SM.root cHWB_int.root;
/home/nyykki/root/bin/hadd -f SM_cHWB_quad.root SM.root cHWB_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWB_int_quad.root SM.root cHWB_int.root cHWB_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHbox_int.root SM.root cHbox_int.root;
/home/nyykki/root/bin/hadd -f SM_cHbox_quad.root SM.root cHbox_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHbox_int_quad.root SM.root cHbox_int.root cHbox_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_int.root SM.root cHDD_int.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_quad.root SM.root cHDD_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_int_quad.root SM.root cHDD_int.root cHDD_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHDD_int_quad.root SM.root cHDD_int.root cHDD_quad.root;
/home/nyykki/root/bin/hadd -f SM_cW_int_0.4.root SM.root cW_int_0.4.root;
/home/nyykki/root/bin/hadd -f SM_cW_quad_0.4.root SM.root cW_quad_0.4.root;
/home/nyykki/root/bin/hadd -f SM_cW_int_quad_0.4.root SM.root cW_int_0.4.root cW_quad_0.4.root;
/home/nyykki/root/bin/hadd -f SM_cWtil_int.root SM.root cWtil_int.root;
/home/nyykki/root/bin/hadd -f SM_cWtil_quad.root SM.root cWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cWtil_int_quad.root SM.root cWtil_int.root cWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWtil_int.root SM.root cHWtil_int.root;
/home/nyykki/root/bin/hadd -f SM_cHWtil_quad.root SM.root cHWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWtil_int_quad.root SM.root cHWtil_int.root cHWtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWBtil_int.root SM.root cHWBtil_int.root;
/home/nyykki/root/bin/hadd -f SM_cHWBtil_quad.root SM.root cHWBtil_quad.root;
/home/nyykki/root/bin/hadd -f SM_cHWBtil_int_quad.root SM.root cHWBtil_int.root cHWBtil_quad.root;

cd ../..;

cd histos4datacards;

./merge_multipart mll;

./merge_multipart mjj;

./merge Eta el;
./merge Eta mu;
./merge Eta ta;
./merge Eta j;
./merge PT el;
./merge PT ta;
./merge PT mu;
./merge PT j;

#cd ..;
'''''

./carini Eta_el cW int;
./carini Eta_el cW quad;
./carini Eta_el cW int_quad;
./carini Eta_el cHW int;
./carini Eta_el cHW quad;
./carini Eta_el cHW int_quad;
./carini Eta_el cHWB int;
./carini Eta_el cHWB quad;
./carini Eta_el cHWB int_quad;
./carini Eta_el cHbox int;
./carini Eta_el cHbox quad;
./carini Eta_el cHbox int_quad;
./carini Eta_el cHDD int;
./carini Eta_el cHDD quad;
./carini Eta_el cHDD int_quad;
./carini Eta_el cW int_04;
./carini Eta_el cW quad_04;
./carini Eta_el cW int_quad_04;
./carini Eta_el cWtil int;
./carini Eta_el cWtil quad;
./carini Eta_el cWtil int_quad;
./carini Eta_el cHWtil int;
./carini Eta_el cHWtil quad;
./carini Eta_el cHWtil int_quad;
./carini Eta_el cHWBtil int;
./carini Eta_el cHWBtil quad;
./carini Eta_el cHWBtil int_quad;

./carini Eta_ta cW int;
./carini Eta_ta cW quad;
./carini Eta_ta cW int_quad;
./carini Eta_ta cHW int;
./carini Eta_ta cHW quad;
./carini Eta_ta cHW int_quad;
./carini Eta_ta cHWB int;
./carini Eta_ta cHWB quad;
./carini Eta_ta cHWB int_quad;
./carini Eta_ta cHbox int;
./carini Eta_ta cHbox quad;
./carini Eta_ta cHbox int_quad;
./carini Eta_ta cHDD int;
./carini Eta_ta cHDD quad;
./carini Eta_ta cHDD int_quad;
./carini Eta_ta cW int_04;
./carini Eta_ta cW quad_04;
./carini Eta_ta cW int_quad_04;
./carini Eta_ta cWtil int;
./carini Eta_ta cWtil quad;
./carini Eta_ta cWtil int_quad;
./carini Eta_ta cHWtil int;
./carini Eta_ta cHWtil quad;
./carini Eta_ta cHWtil int_quad;
./carini Eta_ta cHWBtil int;
./carini Eta_ta cHWBtil quad;
./carini Eta_ta cHWBtil int_quad;

./carini Eta_mu cW int;
./carini Eta_mu cW quad;
./carini Eta_mu cW int_quad;
./carini Eta_mu cHW int;
./carini Eta_mu cHW quad;
./carini Eta_mu cHW int_quad;
./carini Eta_mu cHWB int;
./carini Eta_mu cHWB quad;
./carini Eta_mu cHWB int_quad;
./carini Eta_mu cHbox int;
./carini Eta_mu cHbox quad;
./carini Eta_mu cHbox int_quad;
./carini Eta_mu cHDD int;
./carini Eta_mu cHDD quad;
./carini Eta_mu cHDD int_quad;
./carini Eta_mu cW int_04;
./carini Eta_mu cW quad_04;
./carini Eta_mu cW int_quad_04;
./carini Eta_mu cWtil int;
./carini Eta_mu cWtil quad;
./carini Eta_mu cWtil int_quad;
./carini Eta_mu cHWtil int;
./carini Eta_mu cHWtil quad;
./carini Eta_mu cHWtil int_quad;
./carini Eta_mu cHWBtil int;
./carini Eta_mu cHWBtil quad;
./carini Eta_mu cHWBtil int_quad;

./carini Eta_j cW int;
./carini Eta_j cW quad;
./carini Eta_j cW int_quad;
./carini Eta_j cHW int;
./carini Eta_j cHW quad;
./carini Eta_j cHW int_quad;
./carini Eta_j cHWB int;
./carini Eta_j cHWB quad;
./carini Eta_j cHWB int_quad;
./carini Eta_j cHbox int;
./carini Eta_j cHbox quad;
./carini Eta_j cHbox int_quad;
./carini Eta_j cHDD int;
./carini Eta_j cHDD quad;
./carini Eta_j cHDD int_quad;
./carini Eta_j cW int_04;
./carini Eta_j cW quad_04;
./carini Eta_j cW int_quad_04;
./carini Eta_j cWtil int;
./carini Eta_j cWtil quad;
./carini Eta_j cWtil int_quad;
./carini Eta_j cHWtil int;
./carini Eta_j cHWtil quad;
./carini Eta_j cHWtil int_quad;
./carini Eta_j cHWBtil int;
./carini Eta_j cHWBtil quad;
./carini Eta_j cHWBtil int_quad;

./carini PT_j cW int;
./carini PT_j cW quad;
./carini PT_j cW int_quad;
./carini PT_j cHW int;
./carini PT_j cHW quad;
./carini PT_j cHW int_quad;
./carini PT_j cHWB int;
./carini PT_j cHWB quad;
./carini PT_j cHWB int_quad;
./carini PT_j cHbox int;
./carini PT_j cHbox quad;
./carini PT_j cHbox int_quad;
./carini PT_j cHDD int;
./carini PT_j cHDD quad;
./carini PT_j cHDD int_quad;
./carini PT_j cW int_04;
./carini PT_j cW quad_04;
./carini PT_j cW int_quad_04;
./carini PT_j cWtil int;
./carini PT_j cWtil quad;
./carini PT_j cWtil int_quad;
./carini PT_j cHWtil int;
./carini PT_j cHWtil quad;
./carini PT_j cHWtil int_quad;
./carini PT_j cHWBtil int;
./carini PT_j cHWBtil quad;
./carini PT_j cHWBtil int_quad;

./carini PT_el cW int;
./carini PT_el cW quad;
./carini PT_el cW int_quad;
./carini PT_el cHW int;
./carini PT_el cHW quad;
./carini PT_el cHW int_quad;
./carini PT_el cHWB int;
./carini PT_el cHWB quad;
./carini PT_el cHWB int_quad;
./carini PT_el cHbox int;
./carini PT_el cHbox quad;
./carini PT_el cHbox int_quad;
./carini PT_el cHDD int;
./carini PT_el cHDD quad;
./carini PT_el cHDD int_quad;
./carini PT_el cW int_04;
./carini PT_el cW quad_04;
./carini PT_el cW int_quad_04;
./carini PT_el cWtil int;
./carini PT_el cWtil quad;
./carini PT_el cWtil int_quad;
./carini PT_el cHWtil int;
./carini PT_el cHWtil quad;
./carini PT_el cHWtil int_quad;
./carini PT_el cHWBtil int;
./carini PT_el cHWBtil quad;
./carini PT_el cHWBtil int_quad;

./carini PT_mu cW int;
./carini PT_mu cW quad;
./carini PT_mu cW int_quad;
./carini PT_mu cHW int;
./carini PT_mu cHW quad;
./carini PT_mu cHW int_quad;
./carini PT_mu cHWB int;
./carini PT_mu cHWB quad;
./carini PT_mu cHWB int_quad;
./carini PT_mu cHbox int;
./carini PT_mu cHbox quad;
./carini PT_mu cHbox int_quad;
./carini PT_mu cHDD int;
./carini PT_mu cHDD quad;
./carini PT_mu cHDD int_quad;
./carini PT_mu cW int_04;
./carini PT_mu cW quad_04;
./carini PT_mu cW int_quad_04;
./carini PT_mu cWtil int;
./carini PT_mu cWtil quad;
./carini PT_mu cWtil int_quad;
./carini PT_mu cHWtil int;
./carini PT_mu cHWtil quad;
./carini PT_mu cHWtil int_quad;
./carini PT_mu cHWBtil int;
./carini PT_mu cHWBtil quad;
./carini PT_mu cHWBtil int_quad;

./carini PT_ta cW int;
./carini PT_ta cW quad;
./carini PT_ta cW int_quad;
./carini PT_ta cHW int;
./carini PT_ta cHW quad;
./carini PT_ta cHW int_quad;
./carini PT_ta cHWB int;
./carini PT_ta cHWB quad;
./carini PT_ta cHWB int_quad;
./carini PT_ta cHbox int;
./carini PT_ta cHbox quad;
./carini PT_ta cHbox int_quad;
./carini PT_ta cHDD int;
./carini PT_ta cHDD quad;
./carini PT_ta cHDD int_quad;
./carini PT_ta cW int_04;
./carini PT_ta cW quad_04;
./carini PT_ta cW int_quad_04;
./carini PT_ta cWtil int;
./carini PT_ta cWtil quad;
./carini PT_ta cWtil int_quad;
./carini PT_ta cHWtil int;
./carini PT_ta cHWtil quad;
./carini PT_ta cHWtil int_quad;
./carini PT_ta cHWBtil int;
./carini PT_ta cHWBtil quad;
./carini PT_ta cHWBtil int_quad;

./carini mll cW int;
./carini mll cW quad;
./carini mll cW int_quad;
./carini mll cHW int;
./carini mll cHW quad;
./carini mll cHW int_quad;
./carini mll cHWB int;
./carini mll cHWB quad;
./carini mll cHWB int_quad;
./carini mll cHbox int;
./carini mll cHbox quad;
./carini mll cHbox int_quad;
./carini mll cHDD int;
./carini mll cHDD quad;
./carini mll cHDD int_quad;
./carini mll cW int_04;
./carini mll cW quad_04;
./carini mll cW int_quad_04;
./carini mll cWtil int;
./carini mll cWtil quad;
./carini mll cWtil int_quad;
./carini mll cHWtil int;
./carini mll cHWtil quad;
./carini mll cHWtil int_quad;
./carini mll cHWBtil int;
./carini mll cHWBtil quad;
./carini mll cHWBtil int_quad;

./carini mjj cW int;
./carini mjj cW quad;
./carini mjj cW int_quad;
./carini mjj cHW int;
./carini mjj cHW quad;
./carini mjj cHW int_quad;
./carini mjj cHWB int;
./carini mjj cHWB quad;
./carini mjj cHWB int_quad;
./carini mjj cHbox int;
./carini mjj cHbox quad;
./carini mjj cHbox int_quad;
./carini mjj cHDD int;
./carini mjj cHDD quad;
./carini mjj cHDD int_quad;
./carini mjj cW int_04;
./carini mjj cW quad_04;
./carini mjj cW int_quad_04;
./carini mjj cWtil int;
./carini mjj cWtil quad;
./carini mjj cWtil int_quad;
./carini mjj cHWtil int;
./carini mjj cHWtil quad;
./carini mjj cHWtil int_quad;
./carini mjj cHWBtil int;
./carini mjj cHWBtil quad;
./carini mjj cHWBtil int_quad;


./cariniCV Eta_el cW int;
./cariniCV Eta_el cW quad;
./cariniCV Eta_el cW int_quad;
./cariniCV Eta_el cHW int;
./cariniCV Eta_el cHW quad;
./cariniCV Eta_el cHW int_quad;
./cariniCV Eta_el cHWB int;
./cariniCV Eta_el cHWB quad;
./cariniCV Eta_el cHWB int_quad;
./cariniCV Eta_el cHbox int;
./cariniCV Eta_el cHbox quad;
./cariniCV Eta_el cHbox int_quad;
./cariniCV Eta_el cHDD int;
./cariniCV Eta_el cHDD quad;
./cariniCV Eta_el cHDD int_quad;

./cariniCV Eta_ta cW int;
./cariniCV Eta_ta cW quad;
./cariniCV Eta_ta cW int_quad;
./cariniCV Eta_ta cHW int;
./cariniCV Eta_ta cHW quad;
./cariniCV Eta_ta cHW int_quad;
./cariniCV Eta_ta cHWB int;
./cariniCV Eta_ta cHWB quad;
./cariniCV Eta_ta cHWB int_quad;
./cariniCV Eta_ta cHbox int;
./cariniCV Eta_ta cHbox quad;
./cariniCV Eta_ta cHbox int_quad;
./cariniCV Eta_ta cHDD int;
./cariniCV Eta_ta cHDD quad;
./cariniCV Eta_ta cHDD int_quad;

./cariniCV Eta_mu cW int;
./cariniCV Eta_mu cW quad;
./cariniCV Eta_mu cW int_quad;
./cariniCV Eta_mu cHW int;
./cariniCV Eta_mu cHW quad;
./cariniCV Eta_mu cHW int_quad;
./cariniCV Eta_mu cHWB int;
./cariniCV Eta_mu cHWB quad;
./cariniCV Eta_mu cHWB int_quad;
./cariniCV Eta_mu cHbox int;
./cariniCV Eta_mu cHbox quad;
./cariniCV Eta_mu cHbox int_quad;
./cariniCV Eta_mu cHDD int;
./cariniCV Eta_mu cHDD quad;
./cariniCV Eta_mu cHDD int_quad;

./cariniCV Eta_j cW int;
./cariniCV Eta_j cW quad;
./cariniCV Eta_j cW int_quad;
./cariniCV Eta_j cHW int;
./cariniCV Eta_j cHW quad;
./cariniCV Eta_j cHW int_quad;
./cariniCV Eta_j cHWB int;
./cariniCV Eta_j cHWB quad;
./cariniCV Eta_j cHWB int_quad;
./cariniCV Eta_j cHbox int;
./cariniCV Eta_j cHbox quad;
./cariniCV Eta_j cHbox int_quad;
./cariniCV Eta_j cHDD int;
./cariniCV Eta_j cHDD quad;
./cariniCV Eta_j cHDD int_quad;

./cariniCV PT_j cW int;
./cariniCV PT_j cW quad;
./cariniCV PT_j cW int_quad;
./cariniCV PT_j cHW int;
./cariniCV PT_j cHW quad;
./cariniCV PT_j cHW int_quad;
./cariniCV PT_j cHWB int;
./cariniCV PT_j cHWB quad;
./cariniCV PT_j cHWB int_quad;
./cariniCV PT_j cHbox int;
./cariniCV PT_j cHbox quad;
./cariniCV PT_j cHbox int_quad;
./cariniCV PT_j cHDD int;
./cariniCV PT_j cHDD quad;
./cariniCV PT_j cHDD int_quad;

./cariniCV PT_el cW int;
./cariniCV PT_el cW quad;
./cariniCV PT_el cW int_quad;
./cariniCV PT_el cHW int;
./cariniCV PT_el cHW quad;
./cariniCV PT_el cHW int_quad;
./cariniCV PT_el cHWB int;
./cariniCV PT_el cHWB quad;
./cariniCV PT_el cHWB int_quad;
./cariniCV PT_el cHbox int;
./cariniCV PT_el cHbox quad;
./cariniCV PT_el cHbox int_quad;
./cariniCV PT_el cHDD int;
./cariniCV PT_el cHDD quad;
./cariniCV PT_el cHDD int_quad;

./cariniCV PT_mu cW int;
./cariniCV PT_mu cW quad;
./cariniCV PT_mu cW int_quad;
./cariniCV PT_mu cHW int;
./cariniCV PT_mu cHW quad;
./cariniCV PT_mu cHW int_quad;
./cariniCV PT_mu cHWB int;
./cariniCV PT_mu cHWB quad;
./cariniCV PT_mu cHWB int_quad;
./cariniCV PT_mu cHbox int;
./cariniCV PT_mu cHbox quad;
./cariniCV PT_mu cHbox int_quad;
./cariniCV PT_mu cHDD int;
./cariniCV PT_mu cHDD quad;
./cariniCV PT_mu cHDD int_quad;

./cariniCV PT_ta cW int;
./cariniCV PT_ta cW quad;
./cariniCV PT_ta cW int_quad;
./cariniCV PT_ta cHW int;
./cariniCV PT_ta cHW quad;
./cariniCV PT_ta cHW int_quad;
./cariniCV PT_ta cHWB int;
./cariniCV PT_ta cHWB quad;
./cariniCV PT_ta cHWB int_quad;
./cariniCV PT_ta cHbox int;
./cariniCV PT_ta cHbox quad;
./cariniCV PT_ta cHbox int_quad;
./cariniCV PT_ta cHDD int;
./cariniCV PT_ta cHDD quad;
./cariniCV PT_ta cHDD int_quad;

./cariniCV mll cW int;
./cariniCV mll cW quad;
./cariniCV mll cW int_quad;
./cariniCV mll cHW int;
./cariniCV mll cHW quad;
./cariniCV mll cHW int_quad;
./cariniCV mll cHWB int;
./cariniCV mll cHWB quad;
./cariniCV mll cHWB int_quad;
./cariniCV mll cHbox int;
./cariniCV mll cHbox quad;
./cariniCV mll cHbox int_quad;
./cariniCV mll cHDD int;
./cariniCV mll cHDD quad;
./cariniCV mll cHDD int_quad;

./cariniCV mjj cW int;
./cariniCV mjj cW quad;
./cariniCV mjj cW int_quad;
./cariniCV mjj cHW int;
./cariniCV mjj cHW quad;
./cariniCV mjj cHW int_quad;
./cariniCV mjj cHWB int;
./cariniCV mjj cHWB quad;
./cariniCV mjj cHWB int_quad;
./cariniCV mjj cHbox int;
./cariniCV mjj cHbox quad;
./cariniCV mjj cHbox int_quad;
./cariniCV mjj cHDD int;
./cariniCV mjj cHDD quad;
./cariniCV mjj cHDD int_quad;

'''''


