(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}, {SMHLOOP, 0}, {NP, 0}, {NPshifts, 0}, {NPprop, 0}, {NPcpv, 0}, {NPcdB, 0}, {NPcdd, 0}, {NPcdd1, 0}, {NPcdG, 0}, {NPcdH, 0}, {NPcdW, 0}, {NPceB, 0}, {NPced, 0}, {NPcee, 0}, {NPceH, 0}, {NPceu, 0}, {NPceW, 0}, {NPcG, 0}, {NPcGtil, 0}, {NPcH, 0}, {NPcHB, 0}, {NPcHbox, 0}, {NPcHBtil, 0}, {NPcHd, 0}, {NPcHDD, 0}, {NPcHe, 0}, {NPcHG, 0}, {NPcHGtil, 0}, {NPcHl1, 0}, {NPcHl3, 0}, {NPcHq1, 0}, {NPcHq3, 0}, {NPcHu, 0}, {NPcHud, 0}, {NPcHW, 0}, {NPcHWB, 0}, {NPcHWBtil, 0}, {NPcHWtil, 0}, {NPcld, 0}, {NPcle, 0}, {NPcledq, 0}, {NPclequ1, 0}, {NPclequ3, 0}, {NPcll, 0}, {NPcll1, 0}, {NPclq1, 0}, {NPclq3, 0}, {NPclu, 0}, {NPcqd1, 0}, {NPcqd8, 0}, {NPcqe, 0}, {NPcqq1, 0}, {NPcqq11, 0}, {NPcqq3, 0}, {NPcqq31, 0}, {NPcqu1, 0}, {NPcqu8, 0}, {NPcquqd1, 0}, {NPcquqd11, 0}, {NPcquqd8, 0}, {NPcquqd81, 0}, {NPcuB, 0}, {NPcud1, 0}, {NPcud8, 0}, {NPcuG, 0}, {NPcuH, 0}, {NPcuu, 0}, {NPcuu1, 0}, {NPcuW, 0}, {NPcW, 0}, {NPcWtil, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

V[13] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Superscript[Z,,]",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ1,
    Indices -> {} },

V[14] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "Superscript[W,,]",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW1,
    Indices -> {} },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

F[31] == {
    Indices -> {Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "Superscript[t,,]",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MT1 },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} },

S[4] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Superscript[H,,]",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH1,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W]

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
MZ1[ ___ ] := MZ1;
MW1[ ___ ] := MW1;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MT1[ ___ ] := MT1;
MH[ ___ ] := MH;
MH1[ ___ ] := MH1


TheLabel[ V[4, {1}] ] = "G";
TheLabel[ U[4, {1}] ] = "uG";
TheLabel[ F[1, {1}] ] = "ve";
TheLabel[ F[1, {2}] ] = "vm";
TheLabel[ F[1, {3}] ] = "vt";
TheLabel[ F[2, {1}] ] = "e";
TheLabel[ F[2, {2}] ] = "mu";
TheLabel[ F[2, {3}] ] = "ta";
TheLabel[ F[3, {1, _}] ] = "u";
TheLabel[ F[3, {1}] ] = "u";
TheLabel[ F[3, {2, _}] ] = "c";
TheLabel[ F[3, {2}] ] = "c";
TheLabel[ F[3, {3, _}] ] = "t";
TheLabel[ F[3, {3}] ] = "t";
TheLabel[ F[4, {1, _}] ] = "d";
TheLabel[ F[4, {1}] ] = "d";
TheLabel[ F[4, {2, _}] ] = "s";
TheLabel[ F[4, {2}] ] = "s";
TheLabel[ F[4, {3, _}] ] = "b";
TheLabel[ F[4, {3, _}] ] = "b";
TheLabel[ F[31, {1, _}] ] = "Superscript[t,,]"


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[1] , S[1] , S[1] , S[1] ] == {{((6*I)*lam*(-1 + sth)*(1 + sth)*(LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2))/(cth^2*LambdaSMEFT^2), 0}},

C[ S[1] , S[1] , S[1] ] == {{((3*I)*lam*(-1 + sth)*(1 + sth)*vevhat*(2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2))/(cth^2*LambdaSMEFT^2), 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc3*SUNF[e1x2, e2x2, e3x2]), 0}, {gc3*SUNF[e1x2, e2x2, e3x2], 0}, {gc3*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc3*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc3*SUNF[e1x2, e2x2, e3x2]), 0}, {gc3*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc4*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc4*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc4*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc5*IndexDelta[e1x2, e2x2], 0}, {I*gc5*IndexDelta[e1x2, e2x2], 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc6, 0}, {I*gc6, 0}, {I*gc6, 0}, {(-I)*gc6, 0}, {(-I)*gc6, 0}, {I*gc6, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((-I/2)*EL^2*(-1 + sth)*(1 + sth)*(LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2))/(cth^2*LambdaSMEFT^2*sth^2), 0}},

C[ S[1] , V[3] , -V[3] ] == {{((-I/4)*EL^2*(-1 + sth)*(1 + sth)*vevhat*(2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2))/(cth^2*LambdaSMEFT^2*sth^2), 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc9, 0}, {(-I)*gc9, 0}, {(2*I)*gc9, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc10, 0}, {I*gc10, 0}, {I*gc10, 0}, {(-I)*gc10, 0}, {(-I)*gc10, 0}, {I*gc10, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc11, 0}, {(-I)*gc11, 0}, {(2*I)*gc11, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc12L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc12R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc13L[e1x2, e2x2], 0}, {I*gc13R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc14L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc14R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc15, 0}, {I*gc15, 0}, {I*gc15, 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*(LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2))/(cth^2*LambdaSMEFT^2*sth^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/4)*EL^2*vevhat*(2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2))/(cth^2*LambdaSMEFT^2*sth^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc18, 0}, {(-I)*gc18, 0}, {(2*I)*gc18, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc19*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc19*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc20*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc20*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc21*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc21*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc22*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc22*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc23[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , S[1] , V[3] ] == {{I*gc24[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[3] ] == {{I*gc25[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc26*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc27[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , S[1] , -V[3] ] == {{I*gc28[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , -V[3] ] == {{I*gc29[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc30*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc31L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc31R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , S[1] , V[2] ] == {{I*gc32*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] , V[2] ] == {{I*gc33*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc34L*IndexDelta[e1x2, e2x2], 0}, {I*gc34R*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc35L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc35R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , S[1] , V[2] ] == {{I*gc36*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] , V[2] ] == {{I*gc37*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc38*IndexDelta[e1x2, e2x2], 0}, {0, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc3 -> GS,
     gc4 -> -GS^2,
     gc5 -> (EL*(2*cHWB*(-1 + sth^2)*vevhat^2 + cth*sth*(2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2)))/(2*cth*LambdaSMEFT^2*sth),
     gc6 -> -(EL*(2 + ((-2*cHWB*cth + (-2*cHl3 + 4*cHW + cll1)*sth)*vevhat^2)/(LambdaSMEFT^2*sth)))/2,
     gc9 -> -((EL^2*(LambdaSMEFT^2*sth + (-2*cHWB*cth + (-2*cHl3 + 2*cHW + cll1)*sth)*vevhat^2))/(LambdaSMEFT^2*sth)),
     gc10 -> -(EL*(2*cth*LambdaSMEFT^2 + (-2*cHl3 + 4*cHW + cll1)*cth*vevhat^2 + 2*cHWB*sth*vevhat^2))/(2*LambdaSMEFT^2*sth),
     gc11 -> (EL^2*(LambdaSMEFT^2 + (-2*cHl3 + 2*cHW + cll1)*vevhat^2))/(LambdaSMEFT^2*sth^2),
     gc12L[e1x2_, e2x2_] -> -((2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2)*yd[e1x2, e2x2])/(2*Sqrt[2]*LambdaSMEFT^2),
     gc12R[e1x2_, e2x2_] -> -((2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2)*yd[e2x2, e1x2])/(2*Sqrt[2]*LambdaSMEFT^2),
     gc13L[e1x2_, e2x2_] -> -((2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2)*yl[e1x2, e2x2])/(2*Sqrt[2]*LambdaSMEFT^2),
     gc13R[e1x2_, e2x2_] -> -((2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2)*yl[e2x2, e1x2])/(2*Sqrt[2]*LambdaSMEFT^2),
     gc14L[e1x2_, e2x2_] -> -((2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2)*yu[e1x2, e2x2])/(2*Sqrt[2]*LambdaSMEFT^2),
     gc14R[e1x2_, e2x2_] -> -((2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2)*yu[e2x2, e1x2])/(2*Sqrt[2]*LambdaSMEFT^2),
     gc15 -> (EL^2*(cHWB*(-1 + 2*sth^2)*vevhat^2 + cth*sth*(LambdaSMEFT^2 + (-2*cHl3 + 2*cHW + cll1)*vevhat^2)))/(LambdaSMEFT^2*sth^2),
     gc18 -> (EL^2*(LambdaSMEFT^2*(-1 + sth^2) + (2*cHl3 - 2*cHW - cll1 - 2*cHWB*cth*sth + (-2*cHl3 + 2*cHW + cll1)*sth^2)*vevhat^2))/(LambdaSMEFT^2*sth^2),
     gc19 -> (EL*(2*cHWB*(-1 + sth^2)*vevhat^2 + cth*sth*(2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2)))/(6*cth*LambdaSMEFT^2*sth),
     gc20 -> -(EL*(2*cHWB*(-1 + sth^2)*vevhat^2 + cth*sth*(2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2)))/(3*cth*LambdaSMEFT^2*sth),
     gc21 -> -GS,
     gc22 -> -GS,
     gc23[e1x2_, e2x2_] -> -(EL*(2*LambdaSMEFT^2 + (-2*cHl3 + 2*cHq3 + cll1)*vevhat^2)*CKM[e1x2, e2x2])/(2*Sqrt[2]*LambdaSMEFT^2*sth),
     gc24[e1x2_, e2x2_] -> -((Sqrt[2]*cHq3*EL*CKM[e1x2, e2x2])/(LambdaSMEFT^2*sth)),
     gc25[e1x2_, e2x2_] -> -((Sqrt[2]*cHq3*EL*vevhat*CKM[e1x2, e2x2])/(LambdaSMEFT^2*sth)),
     gc26 -> -(EL*(2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2))/(2*Sqrt[2]*LambdaSMEFT^2*sth),
     gc27[e1x2_, e2x2_] -> -(EL*(2*LambdaSMEFT^2 + (-2*cHl3 + 2*cHq3 + cll1)*vevhat^2)*Conjugate[CKM[e2x2, e1x2]])/(2*Sqrt[2]*LambdaSMEFT^2*sth),
     gc28[e1x2_, e2x2_] -> -((Sqrt[2]*cHq3*EL*Conjugate[CKM[e2x2, e1x2]])/(LambdaSMEFT^2*sth)),
     gc29[e1x2_, e2x2_] -> -((Sqrt[2]*cHq3*EL*vevhat*Conjugate[CKM[e2x2, e1x2]])/(LambdaSMEFT^2*sth)),
     gc30 -> -(EL*(2*LambdaSMEFT^2 + (-2*cHl3 + cll1)*vevhat^2))/(2*Sqrt[2]*LambdaSMEFT^2*sth),
     gc31L -> (6*EL*LambdaSMEFT^2 - 4*EL*LambdaSMEFT^2*sth^2 + 3*(-2*cHl3 + 2*cHq3 + cll1)*EL*vevhat^2 + 4*cHWB*cth*EL*sth*vevhat^2 + (4*cHl3*EL - 2*cll1*EL)*sth^2*vevhat^2)/(12*cth*LambdaSMEFT^2*sth),
     gc31R -> (EL*(-2*LambdaSMEFT^2*sth + (2*cHWB*cth + 2*cHl3*sth - cll1*sth)*vevhat^2))/(6*cth*LambdaSMEFT^2),
     gc32 -> (cHq3*EL)/(cth*LambdaSMEFT^2*sth),
     gc33 -> (cHq3*EL*vevhat)/(cth*LambdaSMEFT^2*sth),
     gc34L -> (2*EL*LambdaSMEFT^2 - 4*EL*LambdaSMEFT^2*sth^2 + (-2*cHl3 + cll1)*EL*vevhat^2 + 4*cHWB*cth*EL*sth*vevhat^2 + (4*cHl3*EL - 2*cll1*EL)*sth^2*vevhat^2)/(4*cth*LambdaSMEFT^2*sth),
     gc34R -> (EL*(-2*LambdaSMEFT^2*sth + (2*cHWB*cth + 2*cHl3*sth - cll1*sth)*vevhat^2))/(2*cth*LambdaSMEFT^2),
     gc35L -> (-6*EL*LambdaSMEFT^2 + 8*EL*LambdaSMEFT^2*sth^2 - 3*(-2*cHl3 + 2*cHq3 + cll1)*EL*vevhat^2 - 8*cHWB*cth*EL*sth*vevhat^2 - (8*cHl3*EL - 4*cll1*EL)*sth^2*vevhat^2)/(12*cth*LambdaSMEFT^2*sth),
     gc35R -> (EL*(2*LambdaSMEFT^2*sth + (-2*cHWB*cth + (-2*cHl3 + cll1)*sth)*vevhat^2))/(3*cth*LambdaSMEFT^2),
     gc36 -> -((cHq3*EL)/(cth*LambdaSMEFT^2*sth)),
     gc37 -> -((cHq3*EL*vevhat)/(cth*LambdaSMEFT^2*sth)),
     gc38 -> (-2*EL*LambdaSMEFT^2 - (-2*cHl3 + cll1)*EL*vevhat^2)/(4*cth*LambdaSMEFT^2*sth)}

